export const generation1Moves = ['absorb', 'acid', 'acid-armor', 'agility', 'amnesia', 'aurora-beam', 'barrage', 'barrier', 'bide', 
    'bind', 'bite', 'blizzard', 'body-slam', 'bone-club', 'bonemerang', 'bubble', 'bubble-beam', 'clamp', 'comet-punch', 'confuse-ray', 
    'confusion', 'constrict', 'conversion', 'counter', 'crabhammer', 'cut', 'defense-curl', 'dig', 'disable', 'dizzy-punch', 
    'double-kick', 'double-slap', 'double-team', 'double-edge', 'dragon-rage', 'dream-eater', 'drill-peck', 'earthquake', 'egg-bomb', 
    'ember', 'explosion', 'fire-blast', 'fire-punch', 'fissure', 'flamethrower', 'flash', 'fly', 'focus-energy', 'fury-attack', 
    'fury-swipes', 'glare', 'growl', 'growth', 'guillotine', 'gust', 'harden', 'haze', 'headbutt', 'high-jump-kick', 'horn-attack', 
    'hydro-pump', 'hyper-beam', 'hyper-fang', 'hypnosis', 'ice-beam', 'ice-punch', 'karate-chop', 'kinesis', 'leech-life', 'leech-seed', 
    'leer', 'lick', 'light-screen', 'lovely-kiss', 'low-kick', 'meditate', 'mega-drain', 'mega-kick', 'mega-punch', 'metronome', 'mimic', 
    'minimize', 'mirror-move', 'mist', 'night-shade', 'pay-day', 'peck', 'petal-dance', 'pin-missile', 'poison-gas', 'poison-powder', 
    'poison-sting', 'pound', 'psybeam', 'psychic', 'psywave', 'quick-attack', 'rage', 'razor-leaf', 'razor-wind', 'recover', 'reflect', 
    'rest', 'roar', 'rock-slide', 'rock-throw', 'rolling-kick', 'sand-attack', 'scratch', 'screech', 'seismic-toss', 'self-destruct', 
    'sharpen', 'sing', 'skull-bash', 'sky-attack', 'slam', 'slash', 'sleep-powder', 'sludge', 'smog', 'smokescreen', 'soft-boiled', 
    'solar-beam', 'sonic-boom', 'spike-cannon', 'splash', 'spore', 'stomp', 'strength', 'string-shot', 'struggle', 'stun-spore', 
    'submission', 'substitute', 'super-fang', 'supersonic', 'surf', 'swift', 'swords-dance', 'tackle', 'tail-whip', 'take-down', 
    'thrash', 'thunder', 'thunderbolt', 'thunder-punch', 'thunder-shock', 'thunder-wave', 'toxic', 'transform', 'tri-attack', 'twineedle', 
    'vine-whip', 'vice-grip', 'waterfall', 'water-gun', 'whirlwind', 'withdraw', 'wrap'
];

export const generation2Moves = ['absorb', 'acid', 'acid-armor', 'aeroblast', 'agility', 'amnesia', 'ancient-power', 'attract', 
    'aurora-beam', 'barrage', 'barrier', 'baton-pass', 'beat-up', 'belly-drum', 'bide', 'bind', 'bite', 'blizzard', 'body-slam', 
    'bonemerang', 'bone-rush', 'bubble', 'bubble-beam', 'charm', 'clamp', 'comet-punch', 'confuse-ray', 'confusion', 
    'constrict', 'conversion', 'conversion-2', 'cotton-spore', 'counter', 'crabhammer', 'cross-chop', 'crunch', 'curse', 'cut', 
    'defense-curl', 'destiny-bond', 'detect', 'dig', 'disable', 'dizzy-punch', 'double-edge', 'double-kick', 'double-slap', 
    'double-team', 'dragon-breath', 'dragon-rage', 'dream-eater', 'drill-peck', 'dynamic-punch', 'earthquake', 'egg-bomb', 'ember', 
    'encore', 'endure', 'explosion', 'extreme-speed', 'feint-attack', 'false-swipe', 'fire-blast', 'fire-punch', 'fire-spin', 'fissure', 
    'flail', 'flamethrower', 'flame-wheel', 'flash', 'fly', 'focus-energy', 'foresight', 'frustration', 'fury-attack', 'fury-cutter', 
    'fury-swipes', 'future-sight', 'giga-drain', 'glare', 'growl', 'growth', 'guillotine', 'gust', 'harden', 'haze', 'headbutt', 
    'heal-bell', 'hidden-power', 'high-jump-kick', 'horn-attack', 'hydro-pump', 'hyper-beam', 'hyper-fang', 'hypnosis', 'ice-beam', 
    'ice-punch', 'icy-wind', 'iron-tail', 'jump-kick', 'karate-chop', 'kinesis', 'leech-life', 'leech-seed', 'leer', 'lick', 
    'light-screen', 'lock-on', 'lovely-kiss', 'low-kick', 'mach-punch', 'magnitude', 'mean-look', 'meditate', 'mega-drain', 'mega-kick', 
    'mega-punch', 'metal-claw', 'metronome', 'milk-drink', 'mimic', 'minimize', 'mirror-coat', 'mirror-move', 'mist', 'moonlight', 
    'morning-sun', 'mud-slap', 'nightmare', 'night-shade', 'octazooka', 'outrage', 'pain-split', 'pay-day', 'peck', 'perish-song', 
    'petal-dance', 'pin-missile', 'poison-gas', 'poison-powder', 'poison-sting', 'pound', 'powder-snow', 'present', 'protect', 'psybeam', 
    'psychic', 'psych-up', 'psywave', 'pursuit', 'quick-attack', 'rage', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-wind', 'recover', 
    'reflect', 'rest', 'return', 'reversal', 'roar', 'rock-slide', 'rock-smash', 'rock-throw', 'rolling-kick', 'rollout', 'sacred-fire', 
    'safeguard', 'sand-attack', 'sandstorm', 'scary-face', 'scratch', 'screech', 'seismic-toss', 'self-destruct', 'shadow-ball', 
    'sharpen', 'sing', 'skull-bash', 'sky-attack', 'slam', 'slash', 'sleep-powder', 'sleep-talk', 'sludge', 'sludge-bomb', 'smog', 
    'smokescreen', 'soft-boiled', 'solar-beam', 'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spite', 'splash', 'spore', 
    'steel-wing', 'stomp', 'strength', 'string-shot', 'struggle', 'stun-spore', 'submission', 'substitute', 'sunny-day', 'super-fang', 
    'supersonic', 'surf', 'swagger', 'sweet-kiss', 'sweeet-scent', 'swift', 'swords-dance', 'tackle', 'tail-whip', 'take-down', 'teleport', 
    'theif', 'thrash', 'thunder','thunderbolt', 'thunder-punch', 'thunder-shock', 'thunder-wave', 'toxic', 'transform', 'tri-attack', 
    'twineedle', 'vice-grip', 'vine-whip', 'vital-throw', 'waterfall', 'water-gun', 'whirlwind', 'wing-attack', 'withdraw', 'wrap', 
    'zap-cannon'];

export const generation3Moves = ['absorb', 'acid', 'acid-armor', 'aerial-ace', 'aeroblast', 'agility', 'air-cutter', 'amnesia', 
    'ancient-power', 'arm-thrust', 'aromatherapy', 'assist', 'astonish', 'attract', 'aurora-beam', 'barrage', 'barrier', 'baton-pass', 
    'beat-up', 'belly-drum', 'bide', 'bind', 'bite', 'blast-burn', 'blaze-kick', 'blizzard', 'block', 'body-slam', 'bone-club', 
    'bonemerang', 'bone-rush', 'bounce', 'brick-break', 'bubble', 'bubble-beam', 'bulk-up', 'bullet-seed', 'calm-mind', 'camoflague', 
    'charge', 'charm', 'clamp', 'comet-punch', 'confuse-ray', 'confusion', 'constrict', 'conversion', 'conversion-2', 'cosmic-power', 
    'cotton-spore', 'counter', 'crabhammer', 'cross-chop', 'crunch', 'crush-claw', 'curse', 'cut', 'defense-curl', 'destiny-bond', 
    'detect', 'dig', 'disable', 'dive', 'dizzy-punch', 'doom-desire', 'double-edge', 'double-kick', 'double-slap', 'double-team', 
    'dragon-breath', 'dragon-claw', 'dragon-dance', 'dragon-rage', 'dream-eater', 'drill-peck', 'dynamic-punch', 'earthquake', 'egg-bomb', 
    'ember', 'encore', 'endeavor', 'endure', 'explosion', 'extrasensory', 'extreme-speed', 'facade', 'feint-attack', 'fake-out', 
    'fake-tears', 'false-swipe', 'feather-dance', 'fire-blast', 'fire-punch', 'fire-spin', 'fissure', 'flail', 'flamethrower', 
    'flame-wheel', 'flash', 'flatter', 'fly', 'focus-energy', 'focus-punch', 'follow-me', 'foresight', 'frenzy-plant', 'frustration', 
    'fury-attack', 'fury-cutter', 'fury-swipes', 'future-sight', 'giga-drain', 'glare', 'growl', 'growth', 'grudge', 
    'guillotine', 'gust', 'hail', 'harden', 'haze', 'headbutt', 'heal-bell', 'heart-swap', 'heat-wave', 'helping-hand', 'hidden-power', 
    'high-jump-kick', 'horn-attack', 'horn-drill', 'howl', 'hydro-cannon', 'hydro-pump', 'hyper-beam', 'hyper-fang', 'hyper-voice', 
    'hypnosis', 'ice-ball', 'ice-beam', 'ice-punch', 'icicle-spear', 'icy-wind', 'imprison', 'ingrain', 'iron-defense', 'iron-tail', 
    'jump-kick', 'karate-chop', 'kinesis', 'knock-off', 'leaf-blade', 'leech-life', 'leech-seed', 'leer', 'lick', 'light-screen', 
    'lock-on', 'lovely-kiss', 'low-kick', 'luster-purge', 'mach-punch', 'magic-coat', 'magical-leaf', 'magnitude', 'mean-look', 'meditate', 
    'mega-drain', 'mega-kick', 'mega-punch','megahorn', 'memento', 'metal-claw', 'metal-sound', 'meteor-mash', 
    'metronome', 'milk-drink', 'mimic', 'mind-reader', 'minimize', 'mirror-coat', 'mirror-move', 'mist', 'mist-ball', 'moonlight', 
    'morning-sun', 'mud-sport', 'mud-slap', 'muddy-water', 'mud-shot', 'nature-power', 'needle-arm', 'night-shade', 'nightmare', 
    'night-shade', 'octazooka', 'odor-sleuth', 'outrage', 'overheat', 'pain-split', 'pay-day', 'peck', 'perish-song', 'petal-dance', 
    'pin-missile', 'poison-gas', 'poison-tail', 'poison-powder', 'poison-sting', 'pound', 'powder-snow', 'present', 'protect', 'psybeam', 
    'psychic', 'psych-up', 'psycho-boost', 'psywave', 'pursuit', 'quick-attack', 'rage', 'rain-dance', 'rapid-spin', 'razor-leaf', 
    'razor-wind', 'recover', 'recycle', 'reflect', 'refresh', 'rest', 'return', 'revenge', 'reversal', 'roar', 'rock-blast', 'rock-tomb', 
    'rock-slide', 'rock-smash', 'rock-throw', 'rolling-kick', 'roleplay', 'rollout', 'sacred-fire', 'safeguard', 'sand-tomb', 
    'sand-attack', 'sandstorm', 'scary-face', 'scratch', 'screech', 'secret-power', 'seismic-toss', 'self-destruct', 'shadow-ball', 
    'sharpen', 'sheer-cold', 'shock-wave', 'sing', 'sketch', 'skill-swap', 'skull-bash', 'sky-attack', 'sky-uppercut', 'slack-off', 'slam', 
    'slash', 'sleep-powder', 'sleep-talk', 'sludge', 'sludge-bomb', 'smog', 'smelling-salts', 'snatch', 'snore', 'smokescreen', 
    'soft-boiled', 'solar-beam', 'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spit-up', 'spite', 'splash', 'spore', 
    'steel-wing', 'stockpile', 'stomp', 'strength', 'string-shot', 'struggle', 'stun-spore', 'submission', 'substitute', 'sunny-day', 
    'super-fang', 'supersonic', 'superpower', 'surf', 'swagger', 'swallow', 'sweet-kiss', 'sweeet-scent', 'swift', 'swords-dance', 'tackle', 
    'tail-glow', 'tail-whip', 'take-down', 'taunt', 'teleport', 'teeter-dance', 'theif', 'thrash', 'thunder','thunderbolt', 'thunder-punch', 
    'thunder-shock', 'thunder-wave', 'tickle', 'toxic', 'transform', 'tri-attack', 'trick', 'triple-kick', 'twister', 'twineedle', 'uproar', 
    'vice-grip', 'vine-whip', 'vital-throw', 'volt-tackle', 'waterfall', 'water-gun', 'water-pulse', 'water-sport', 'water-spout', 
    'whirlwind', 'whirlpool', 'weather-ball', 'wing-attack', 'withdraw', 'wrap', 'will-o-wisp', 'wish', 'yawn', 'zap-cannon'];

export const generation4Moves = ['absorb', 'acid', 'acid-armor', 'acupressure', 'aerial-ace', 'aeroblast', 'agility', 'air-cutter', 
    'air-slash', 'amnesia', 'ancient-power', 'aqua-jet', 'aqua-ring', 'aqua-tail', 'arm-thrust', 'aromatherapy', 'assist', 'assurance', 
    'astonish', 'attack-order', 'attract', 'aura-sphere', 'aurora-beam', 'avalanche', 'barrage', 'barrier', 'baton-pass','beat-up', 
    'belly-drum', 'bide', 'bind', 'bite', 'blast-burn', 'blaze-kick', 'blizzard', 'block', 'body-slam', 'bone-club', 'bonemerang', 
    'bone-rush', 'bounce', 'brave-bird', 'brick-break', 'brine', 'bubble', 'bubble-beam', 'bug-bite', 'bug-buzz', 'bulk-up', 
    'bullet-punch', 'bullet-seed', 'calm-mind', 'camoflague', 'captivate', 'charge', 'charge-beam', 'charm', 'chatter', 'clamp', 
    'close-combat', 'comet-punch', 'confuse-ray', 'confusion', 'constrict', 'conversion', 'conversion-2', 'copycat', 'cosmic-power', 
    'cotton-spore', 'counter', 'covet', 'crabhammer', 'cross-chop', 'cross-poison', 'crunch', 'crush-claw', 'crush-grip', 'curse', 'cut', 
    'dark-pulse', 'dark-void', 'defense-curl', 'defend-order', 'defog', 'destiny-bond', 'detect', 'dig', 'disable', 'discharge', 'dive', 
    'dizzy-punch', 'doom-desire', 'double-hit', 'double-edge', 'double-kick', 'double-slap', 'double-team', 'draco-meteor', 
    'dragon-breath', 'dragon-claw', 'dragon-dance', 'dragon-rage', 'dragon-rush', 'dream-eater', 'drill-peck', 'dynamic-punch', 
    'earth-power', 'earthquake', 'egg-bomb', 'embargo', 'ember', 'encore', 'endeavor', 'endure', 'energy-ball', 'eruption', 'explosion', 
    'extrasensory', 'extreme-speed', 'facade', 'feint-attack', 'fake-out', 'fake-tears', 'false-swipe', 'feather-dance', 'feint', 
    'fire-fang', 'fire-blast', 'fire-punch', 'fire-spin', 'fissure', 'flail', 'flamethrower', 'flame-wheel', 'flare-blitz', 'flash', 
    'flash-cannon', 'flatter', 'fling', 'fly', 'focus-blast', 'focus-energy', 'focus-punch', 'follow-me', 'force-palm', 'foresight', 
    'frenzy-plant', 'frustration', 'fury-attack', 'fury-cutter', 'fury-swipes', 'future-sight', 'gastro-acid', 'giga-drain', 'giga-impact', 
    'glare', 'grass-knot', 'grass-whistle', 'gravity', 'growl', 'growth', 'grudge', 'guard-swap', 'guillotine', 'gunk-shot', 'gust', 
    'gyro-ball', 'hail', 'hammer-arm', 'harden', 'haze', 'headbutt', 'head-smash', 'heal-bell', 'healing-wish', 
    'heart-swap', 'heat-wave', 'helping-hand', 'hidden-power', 'high-jump-kick', 'horn-attack', 'horn-drill', 'howl', 'hydro-cannon', 
    'hydro-pump', 'hyper-beam', 'hyper-fang', 'hyper-voice', 'hypnosis', 'ice-ball', 'ice-beam', 'ice-punch', 'ice-shard', 'icicle-spear', 
    'icy-wind', 'imprison', 'ingrain', 'iron-defense', 'iron-head', 'iron-tail', 'judgement', 'jump-kick', 'karate-chop', 'kinesis', 
    'knock-off', 'last-resort', 'lava-plume', 'leaf-blade', 'leaf-storm', 'leech-life', 'leech-seed', 'leer', 'lick', 'light-screen', 
    'lock-on', 'lovely-kiss', 'low-kick', 'lucky-chant', 'lunar-dance', 'luster-purge', 'mach-punch', 'magic-coat', 'magical-leaf', 
    'magnitude', 'magma-storm', 'magnet-bomb', 'magnet-rise', 'mean-look', 'meditate', 'mega-drain', 'mega-kick', 
    'mega-punch','megahorn', 'memento', 'metal-burst', 'metal-claw', 'metal-sound', 'meteor-mash', 'metronome', 'milk-drink', 'mimic', 
    'mind-reader', 'minimize', 'miracle-eye', 'mirror-coat', 'mirror-move', 'mirror-shot', 'mist', 'mist-ball', 'moonlight', 'morning-sun', 'mud-bomb', 
    'mud-sport', 'mud-slap', 'muddy-water', 'mud-shot', 'nasty-plot', 'natural-gift', 'nature-power', 'needle-arm', 'night-slash', 
    'nightmare', 'night-shade', 'octazooka', 'odor-sleuth', 'outrage', 'ominous-wind', 'overheat', 'pain-split', 'pay-day', 'payback', 
    'peck', 'perish-song', 'petal-dance', 'pin-missile', 'pluck', 'poison-fang', 'poison-jab', 'poison-gas', 'poison-tail', 
    'poison-powder', 'poison-sting', 'pound', 'powder-snow', 'power-gem', 'power-swap', 'power-trick', 'power-whip', 'present', 'protect', 
    'psybeam', 'psychic', 'psych-up', 'psycho-boost', 'psycho-cut', 'psycho-shift', 'psywave', 'punishment', 'pursuit', 'quick-attack', 
    'rage', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-wind', 'recover', 'recycle', 'reflect', 'refresh', 'rest', 'return', 'revenge', 
    'reversal', 'roar', 'roar-of-time', 'rock-blast', 'rock-tomb', 'rock-climb', 'rock-polish', 'rock-wrecker', 'rock-slide', 'rock-smash', 
    'rock-throw', 'rolling-kick', 'roleplay', 'rollout', 'roost', 'sacred-fire', 'safeguard', 'sand-tomb', 'sand-attack', 'sandstorm', 
    'scary-face', 'scratch', 'screech', 'secret-power', 'seed-bomb', 'seed-flare', 'seismic-toss', 'self-destruct', 'shadow-ball', 
    'shadow-claw', 'shadow-force', 'shadow-sneak', 'shadow-punch', 'sharpen', 'sheer-cold', 'shock-wave', 'signal-beam', 'silver-wind', 
    'sing', 'sketch', 'skill-swap', 'skull-bash', 'sky-attack', 'sky-uppercut', 'slack-off', 'slam', 'slash', 'sleep-powder', 'sleep-talk', 
    'sludge', 'sludge-bomb', 'smog', 'smelling-salts', 'snatch', 'snore', 'smokescreen', 'soft-boiled', 'spacial-rend', 'solar-beam', 
    'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spit-up', 'spite', 'splash', 'spore', 'stealth-rock', 'steel-wing', 
    'stockpile', 'stomp', 'stone-edge', 'strength', 'string-shot', 'struggle', 'stun-spore', 'submission', 'substitute', 'sunny-day', 
    'super-fang', 'supersonic', 'superpower', 'surf', 'swagger', 'swallow', 'sweet-kiss', 'sweeet-scent', 'swift', 'switcheroo', 
    'swords-dance', 'synthesis', 'tackle', 'tail-glow', 'tail-whip', 'tailwind', 'take-down', 'taunt', 'teleport', 'teeter-dance', 
    'theif', 'thrash', 'thunder','thunderbolt', 'thunder-punch', 'thunder-fang','thunder-shock', 'thunder-wave', 'tickle', 'torment', 
    'toxic', 'toxic-spikes', 'transform', 'tri-attack', 'trick', 'trick-room', 'triple-kick', 'trump-card', 'twister', 'twineedle', 
    'u-turn', 'uproar', 'vacuum-wave', 'vice-grip', 'vine-whip', 'vital-throw', 'volt-tackle', 'wake-up-slap', 'waterfall', 'water-gun', 
    'water-pulse', 'water-sport', 'water-spout', 'whirlwind', 'whirlpool', 'weather-ball', 'wing-attack', 'withdraw', 'wood-hammer', 
    'worry-seed', 'wrap', 'wring-out', 'will-o-wisp', 'wish', 'x-scissor', 'yawn', 'zap-cannon', 'zen-headbutt'];

export const generation5Moves = ['absorb', 'acid', 'acid-armor', 'acid-spray', 'acrobatics', 'acupressure', 'aerial-ace', 'aeroblast', 
    'after-you', 'agility', 'air-cutter', 'air-slash', 'ally-switch', 'amnesia', 'ancient-power', 'aqua-jet', 'aqua-ring', 'aqua-tail', 
    'arm-thrust', 'aromatherapy', 'assist', 'assurance', 'astonish', 'attack-order', 'attract', 'aura-sphere', 'aurora-beam', 'autotomize', 
    'avalanche', 'barrage', 'barrier', 'baton-pass','beat-up', 'belly-drum', 'bide', 'bind', 'bite', 'blast-burn', 'blaze-kick', 
    'blizzard', 'block', 'blue-flare', 'body-slam', 'bolt-strike', 'bone-club', 'bonemerang', 'bone-rush', 'bounce', 'brave-bird', 
    'brick-break', 'brine', 'bubble', 'bubble-beam', 'bug-bite', 'bug-buzz', 'bulk-up', 'bulldoze','bullet-punch', 'bullet-seed', 
    'calm-mind', 'camoflague', 'captivate', 'charge', 'charge-beam', 'charm', 'chatter', 'chip-away', 'circle-throw', 'clamp', 'clear-smog', 
    'close-combat', 'coil', 'comet-punch', 'confuse-ray', 'confusion', 'constrict', 'conversion', 'conversion-2', 'copycat', 'cosmic-power', 
    'cotton-guard', 'cotton-spore', 'counter', 'covet', 'crabhammer', 'cross-chop', 'cross-poison', 'crunch', 'crush-claw', 'crush-grip', 
    'curse', 'cut', 'dark-pulse', 'dark-void', 'defense-curl', 'defend-order', 'defog', 'destiny-bond', 'detect', 'dig', 'disable', 
    'discharge', 'dive', 'dizzy-punch', 'doom-desire', 'double-hit', 'double-edge', 'double-kick', 'double-slap', 'double-team', 
    'draco-meteor', 'dragon-breath', 'dragon-claw', 'dragon-dance', 'dragon-rage', 'dragon-rush', 'dragon-pulse', 'dragon-tail', 
    'drain-punch', 'dream-eater', 'drill-peck', 'drill-run', 'dual-chop', 'dynamic-punch', 'earth-power', 'earthquake', 'echoed-voice', 
    'egg-bomb', 'electro-ball', 'electroweb', 'embargo', 'ember', 'encore', 'endeavor', 'endure', 'energy-ball', 'entrainment', 'eruption', 
    'explosion', 'extrasensory', 'extreme-speed', 'facade', 'feint-attack', 'fake-out', 'fake-tears', 'false-swipe', 'feather-dance', 
    'feint', 'fiery-dance', 'final-gambit', 'fire-fang', 'fire-blast', 'fire-pledge', 'fire-punch', 'fire-spin', 'fissure', 'flail', 
    'flame-burst', 'flame-charge', 'flamethrower', 'flame-wheel', 'flare-blitz', 'flash', 'flash-cannon', 'flatter', 'fling', 'fly', 
    'focus-blast', 'focus-energy', 'focus-punch', 'follow-me', 'force-palm', 'foresight', 'foul-play', 'freeze-shock', 'frenzy-plant', 
    'frost-breath', 'frustration', 'fury-attack', 'fury-cutter', 'fury-swipes', 'fusion-bolt', 'fusion-flare', 'future-sight', 
    'gastro-acid', 'gear-grind', 'giga-drain', 'giga-impact', 'glaciate', 'glare', 'grass-knot', 'grass-pledge', 'grass-whistle', 
    'gravity', 'growl', 'growth', 'grudge', 'guard-split', 'guard-swap', 'guillotine', 'gunk-shot', 'gust', 'gyro-ball', 'hail', 
    'hammer-arm', 'harden', 'haze', 'headbutt', 'head-charge', 'head-smash', 'heal-bell', 'heal-block', 'heal-order', 'heal-pulse', 
    'healing-wish', 'heart-swap', 'heart-stamp', 'heat-crash', 'heat-wave', 'heavy-slam', 'helping-hand', 'hex', 'hidden-power', 
    'high-jump-kick', 'hone-claws', 'horn-attack', 'horn-drill', 'horn-leech', 'howl', 'hurricane', 'hydro-cannon', 'hydro-pump', 
    'hyper-beam', 'hyper-fang', 'hyper-voice', 'hypnosis', 'ice-ball', 'ice-beam', 'ice-punch', 'ice-shard', 'ice-burn', 'ice-fang', 
    'icicle-crash', 'icicle-spear', 'icy-wind', 'imprison', 'incinerate', 'inferno', 'ingrain', 'iron-defense', 'iron-head', 'iron-tail', 
    'judgement', 'jump-kick', 'karate-chop', 'kinesis', 'knock-off', 'last-resort', 'lava-plume', 'leaf-blade', 'leaf-storm', 'leaf-tornado', 
    'leech-life', 'leech-seed', 'leer', 'lick', 'light-screen', 'lock-on', 'lovely-kiss', 'low-kick', 'low-sweep', 'lucky-chant', 
    'lunar-dance', 'luster-purge', 'mach-punch', 'magic-coat', 'magic-room', 'magical-leaf', 'magnitude', 'magma-storm', 'magnet-bomb', 
    'magnet-rise', 'mean-look', 'meditate', 'me-first', 'mega-drain', 'mega-kick', 'mega-punch','megahorn', 'memento', 'metal-burst', 
    'metal-claw', 'metal-sound', 'meteor-mash', 'metronome', 'milk-drink', 'mimic', 'mind-reader', 'minimize', 'miracle-eye', 'mirror-coat', 
    'mirror-move', 'mirror-shot', 'mist', 'mist-ball', 'moonlight', 'morning-sun', 'mud-bomb', 'mud-sport', 'mud-slap', 'muddy-water', 
    'mud-shot', 'nasty-plot', 'natural-gift', 'nature-power', 'needle-arm', 'night-daze', 'night-slash', 'nightmare', 'night-shade', 
    'octazooka', 'odor-sleuth', 'outrage', 'ominous-wind', 'overheat', 'pain-split', 'pay-day', 'payback', 'peck', 'perish-song', 
    'petal-dance', 'pin-missile', 'pluck', 'poison-fang', 'poison-jab', 'poison-gas', 'poison-tail', 'poison-powder', 'poison-sting', 
    'pound', 'powder-snow', 'power-gem', 'power-swap', 'power-trick', 'power-whip', 'power-split', 'present', 'protect', 'psybeam', 'psychic', 'psych-up', 
    'psycho-boost', 'psycho-cut', 'psycho-shift', 'psyshock', 'psystrike', 'psywave', 'punishment', 'pursuit', 'quash', 'quick-attack', 
    'quick-guard', 'quiver-dance', 'rage', 'rage-powder', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-shell', 'razor-wind', 'recover', 'recycle', 
    'reflect', 'reflect-type', 'refresh', 'relic-song', 'rest', 'return', 'revenge', 'retaliate', 'reversal', 'roar', 'roar-of-time', 
    'rock-blast', 'rock-tomb', 'rock-climb', 'rock-polish', 'rock-wrecker', 'rock-slide', 'rock-smash', 'rock-throw', 'rolling-kick', 
    'roleplay', 'rollout', 'roost', 'round', 'sacred-fire', 'sacred-sword', 'safeguard', 'sand-tomb', 'sand-attack', 'sandstorm', 'scald', 
    'scary-face', 'scratch', 'screech', 'searing-shot', 'secret-power', 'secret-sword', 'seed-bomb', 'seed-flare', 'seismic-toss', 
    'self-destruct', 'shadow-ball', 'shadow-claw', 'shadow-force', 'shadow-sneak', 'shadow-punch', 'sharpen', 'sheer-cold', 'shell-smash', 
    'shift-gear', 'shock-wave', 'signal-beam', 'simple-beam', 'silver-wind', 'sing', 'sketch', 'skill-swap', 'skull-bash', 'sky-attack', 
    'sky-drop', 'sky-uppercut', 'slack-off', 'slam', 'slash', 'sleep-powder', 'sleep-talk', 'sludge', 'sludge-bomb', 'sludge-wave', 
    'smack-down', 'smog', 'smelling-salts', 'snarl', 'snatch', 'snore', 'smokescreen', 'soak', 'soft-boiled', 'spacial-rend', 'solar-beam', 
    'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spit-up', 'spite', 'splash', 'spore', 'stealth-rock', 'steamroller', 
    'steel-wing', 'stockpile', 'stomp', 'stone-edge', 'stored-power', 'storm-throw', 'strength', 'string-shot', 'struggle', 'stun-spore', 
    'submission', 'substitute', 'sucker-punch', 'sunny-day', 'super-fang', 'supersonic', 'superpower', 'surf', 'swagger', 'swallow', 
    'sweet-kiss', 'sweeet-scent', 'swift', 'switcheroo', 'swords-dance', 'synchronoise', 'synthesis', 'tackle', 'tail-glow', 'tail-slap', 
    'tail-whip', 'tailwind', 'take-down', 'taunt', 'techno-blast', 'telekinesis', 'teleport', 'teeter-dance', 'theif', 'thrash', 'thunder',
    'thunderbolt', 'thunder-punch', 'thunder-fang','thunder-shock', 'thunder-wave', 'tickle', 'torment', 'toxic', 'toxic-spikes', 
    'transform', 'tri-attack', 'trick', 'trick-room', 'triple-kick', 'trump-card', 'twister', 'twineedle', 'u-turn', 'uproar', 'v-create',
    'vacuum-wave', 'venoshock', 'vice-grip', 'vine-whip', 'vital-throw', 'volt-tackle', 'wake-up-slap', 'waterfall', 'water-gun', 
    'water-pulse', 'water-pledge', 'water-sport', 'water-spout', 'whirlwind', 'whirlpool', 'weather-ball', 'wide-guard', 'wild-charge', 
    'wing-attack', 'withdraw', 'wood-hammer', 'wonder-room', 'work-up', 'worry-seed', 'wrap', 'wring-out', 'will-o-wisp', 'wish', 
    'x-scissor', 'yawn', 'zap-cannon', 'zen-headbutt'];

export const generation6Moves = ['absorb', 'acid', 'acid-armor', 'acid-spray', 'acrobatics', 'acupressure', 'aerial-ace', 'aeroblast', 
    'after-you', 'agility', 'air-cutter', 'air-slash', 'ally-switch', 'amnesia', 'ancient-power', 'aqua-jet', 'aqua-ring', 'aqua-tail', 
    'arm-thrust', 'aromatherapy', 'aromatic-mist', 'assist', 'assurance', 'astonish', 'attack-order', 'attract', 'aura-sphere', 
    'aurora-beam', 'autotomize', 'avalanche', 'baby-doll-eyes', 'barrage', 'barrier', 'baton-pass','beat-up', 'belch', 'belly-drum', 
    'bestow', 'bide', 'bind', 'bite', 'blast-burn', 'blaze-kick', 'blizzard', 'block', 'blue-flare', 'body-slam', 'bolt-strike', 'bone-club', 
    'bonemerang', 'bone-rush', 'boomburst', 'bounce', 'brave-bird', 'brick-break', 'brine', 'bubble', 'bubble-beam', 'bug-bite', 'bug-buzz', 
    'bulk-up', 'bulldoze','bullet-punch', 'bullet-seed', 'calm-mind', 'camoflague', 'captivate', 'celebrate', 'charge', 'charge-beam', 
    'charm', 'chatter', 'chip-away', 'circle-throw', 'clamp', 'clear-smog', 'close-combat', 'coil', 'comet-punch', 'confuse-ray', 
    'confusion', 'constrict', 'conversion', 'conversion-2', 'copycat', 'cosmic-power', 'cotton-guard', 'cotton-spore', 'counter', 'covet', 
    'crabhammer', 'crafty-shield', 'cross-chop', 'cross-poison', 'crunch', 'crush-claw', 'crush-grip', 'curse', 'cut', 'dark-pulse', 
    'dark-void', 'dazzling-gleam', 'defense-curl', 'defend-order', 'defog', 'destiny-bond', 'detect', 'diamond-storm', 'dig', 'disable', 
    'disarming-voice', 'discharge', 'dive', 'dizzy-punch', 'doom-desire', 'double-hit', 'double-edge', 'double-kick', 'double-slap', 
    'double-team', 'draco-meteor', 'dragon-ascent', 'dragon-breath', 'dragon-claw', 'dragon-dance', 'dragon-rage', 'dragon-rush', 
    'dragon-pulse', 'dragon-tail', 'drain-punch', 'draining-kiss', 'dream-eater', 'drill-peck', 'drill-run', 'dual-chop', 'dynamic-punch', 
    'earth-power', 'earthquake', 'echoed-voice', 'eerie-impulse', 'egg-bomb', 'electric-terrain', 'electrify', 'electro-ball', 
    'electroweb', 'embargo', 'ember', 'encore', 'endeavor', 'endure', 'energy-ball', 'entrainment', 'eruption', 'explosion', 'extrasensory', 
    'extreme-speed', 'facade', 'fairy-lock', 'fairy-wind', 'feint-attack', 'fake-out', 'fake-tears', 'false-swipe', 'feather-dance', 
    'feint', 'fell-stinger', 'fiery-dance', 'final-gambit', 'fire-fang', 'fire-blast', 'fire-pledge', 'fire-punch', 'fire-spin', 'fissure', 
    'flail', 'flame-burst', 'flame-charge', 'flamethrower', 'flame-wheel', 'flare-blitz', 'flash', 'flash-cannon', 'flatter', 'fling', 
    'flower-shield', 'fly', 'flying-press', 'focus-blast', 'focus-energy', 'focus-punch', 'follow-me', 'force-palm', 'forests-curse', 
    'foresight', 'foul-play', 'freeze-shock', 'freeze-dry', 'frenzy-plant', 'frost-breath', 'frustration', 'fury-attack', 'fury-cutter', 
    'fury-swipes', 'fusion-bolt', 'fusion-flare', 'future-sight', 'gastro-acid', 'gear-grind', 'geomancy', 'giga-drain', 'giga-impact', 
    'glaciate', 'glare', 'grass-knot', 'grass-pledge', 'grass-whistle', 'grassy-terrain','gravity', 'growl', 'growth', 'grudge', 
    'guard-split', 'guard-swap', 'guillotine', 'gunk-shot', 'gust', 'gyro-ball', 'hail', 'hammer-arm', 'happy-hour', 'harden', 'haze', 
    'headbutt', 'head-charge', 'head-smash', 'heal-bell', 'heal-block', 'heal-order', 'heal-pulse', 'healing-wish', 'heart-swap', 
    'heart-stamp', 'heat-crash', 'heat-wave', 'heavy-slam', 'helping-hand', 'hex', 'hidden-power', 'high-jump-kick', 'hold-back', 
    'hold-hands', 'hone-claws', 'horn-attack', 'horn-drill', 'horn-leech', 'howl', 'hurricane', 'hydro-cannon', 'hydro-pump', 'hyper-beam', 
    'hyper-fang', 'hyper-voice', 'hyperspace-fury', 'hyperspace-hole', 'hypnosis', 'ice-ball', 'ice-beam', 'ice-punch', 'ice-shard', 
    'ice-burn', 'ice-fang', 'icicle-crash', 'icicle-spear', 'icy-wind', 'imprison', 'incinerate', 'inferno', 'ingrain', 'ion-deluge', 
    'iron-defense', 'iron-head', 'iron-tail', 'judgement', 'jump-kick', 'karate-chop', 'kinesis', 'kings-shield', 'knock-off', 
    'lands-wrath', 'last-resort', 'lava-plume', 'leaf-blade', 'leaf-storm', 'leaf-tornado', 'leech-life', 'leech-seed', 'leer', 'lick', 
    'light-of-ruin', 'light-screen', 'lock-on', 'lovely-kiss', 'low-kick', 'low-sweep', 'lucky-chant', 'lunar-dance', 'luster-purge', 
    'mach-punch', 'magic-coat', 'magic-room', 'magical-leaf', 'magnitude', 'magma-storm', 'magnet-bomb', 'magnet-rise', 'magnetic-flux', 
    'mean-look', 'meditate', 'me-first', 'mega-drain', 'mega-kick', 'mega-punch','megahorn', 'memento', 'metal-burst', 
    'metal-claw', 'metal-sound', 'meteor-mash', 'metronome', 'milk-drink', 'mimic', 'mind-reader', 'minimize', 'miracle-eye', 
    'mirror-coat', 'mirror-move', 'mirror-shot', 'mist', 'mist-ball', 'misty-terrain', 'moonblast', 'moonlight', 'morning-sun', 'mud-bomb', 
    'mud-sport', 'mud-slap', 'muddy-water', 'mud-shot', 'mystical-fire', 'nasty-plot', 'natural-gift', 'nature-power', 'needle-arm', 
    'night-daze', 'night-slash', 'nightmare', 'night-shade', 'noble-roar', 'nuzzle', 'oblivion-wing','octazooka', 'odor-sleuth', 'outrage', 
    'ominous-wind', 'origin-pulse', 'overheat', 'pain-split', 'parabolic-charge', 'parting-shot', 'pay-day', 'payback', 'peck', 
    'perish-song', 'petal-blizzard', 'petal-dance', 'phantom-force', 'pin-missile', 'play-nice', 'play-rough', 'pluck', 'poison-fang', 
    'poison-jab', 'poison-gas', 'poison-tail', 'poison-powder', 'poison-sting', 'pound', 'powder', 'powder-snow', 'power-gem', 
    'power-swap', 'power-trick', 'power-whip', 'power-split', 'precipice-blades', 'present', 'protect', 'psybeam', 
    'psychic', 'psych-up', 'psycho-boost', 'psycho-cut', 'psycho-shift', 'psyshock', 'psystrike', 'psywave', 'punishment', 'pursuit', 
    'quash', 'quick-attack', 'quick-guard', 'quiver-dance', 'rage', 'rage-powder', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-shell', 
    'razor-wind', 'recover', 'recycle', 'reflect', 'reflect-type', 'refresh', 'relic-song', 'rest', 'return', 'revenge', 'retaliate', 
    'reversal', 'roar', 'roar-of-time', 'rock-blast', 'rock-tomb', 'rock-climb', 'rock-polish', 'rock-wrecker', 'rock-slide', 'rock-smash', 
    'rock-throw', 'rolling-kick', 'roleplay', 'rollout', 'roost', 'rototiller', 'round', 'sacred-fire', 'sacred-sword', 'safeguard', 
    'sand-tomb', 'sand-attack', 'sandstorm', 'scald', 'scary-face', 'scratch', 'screech', 'searing-shot', 'secret-power', 'secret-sword', 
    'seed-bomb', 'seed-flare', 'seismic-toss', 'self-destruct', 'shadow-ball', 'shadow-claw', 'shadow-force', 'shadow-sneak', 'shadow-punch', 
    'sharpen', 'sheer-cold', 'shell-smash', 'shift-gear', 'shock-wave', 'signal-beam', 'simple-beam', 'silver-wind', 'sing', 'sketch', 
    'skill-swap', 'skull-bash', 'sky-attack', 'sky-uppercut', 'slack-off', 'slam', 'slash', 'sleep-powder', 'sleep-talk', 
    'sludge', 'sludge-bomb', 'sludge-wave', 'smack-down', 'smog', 'smelling-salts', 'snarl', 'snatch', 'snore', 'smokescreen', 'soak', 
    'soft-boiled', 'spacial-rend', 'solar-beam', 'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spiky-shield', 'spit-up', 
    'spite', 'splash', 'spore', 'stealth-rock', 'steam-eruption', 'steamroller', 'steel-wing', 'sticky-web', 'stockpile', 'stomp', 
    'stone-edge', 'stored-power', 'storm-throw', 'strength', 'string-shot', 'struggle', 'struggle-bug', 'stun-spore', 'submission', 
    'substitute', 'sucker-punch', 'sunny-day', 'super-fang', 'supersonic', 'superpower', 'surf', 'swagger', 'swallow', 'sweet-kiss', 
    'sweeet-scent', 'swift', 'switcheroo', 'swords-dance', 'synchronoise', 'synthesis', 'tackle', 'tail-glow', 'tail-slap', 'tail-whip', 
    'tailwind', 'take-down', 'taunt', 'techno-blast', 'telekinesis', 'teleport', 'teeter-dance', 'theif', 'thousand-arrows', 
    'thousand-waves', 'thrash', 'thunder','thunderbolt', 'thunder-punch', 'thunder-fang','thunder-shock', 'thunder-wave', 'tickle', 
    'topsy-turvy', 'torment', 'toxic', 'toxic-spikes', 'transform', 'tri-attack', 'trick', 'trick-room', 'trick-or-treat', 'triple-kick', 
    'trump-card', 'twister', 'twineedle', 'u-turn', 'uproar', 'v-create','vacuum-wave', 'venom-drench', 'venoshock', 'vice-grip', 
    'vine-whip', 'vital-throw', 'volt-switch', 'volt-tackle', 'wake-up-slap', 'waterfall', 'water-gun', 'water-pulse', 'water-pledge', 
    'water-sport', 'water-shuriken', 'water-spout', 'whirlwind', 'whirlpool', 'weather-ball', 'wide-guard', 'wild-charge', 'wing-attack', 
    'withdraw', 'wood-hammer', 'wonder-room', 'work-up', 'worry-seed', 'wrap', 'wring-out', 'will-o-wisp', 'wish', 'x-scissor', 'yawn', 
    'zap-cannon', 'zen-headbutt'];

    // PLEASE NOTE

    // I was only about 1/8 through Gen 7 before stopping to work on the filtering method used in MoveSelector.svelte
    // meaning generation 7 and generation 8 are incomplete/unfinished. Below Generation 7, and Generation 9, have been
    // fully completed and up-to-date as of 09/05/24.

// export const generation7Moves = ['absorb', 'accelerock', 'acid', 'acid-armor', 'acid-downpour', 'acid-spray', 'acrobatics', 'acupressure', 'aerial-ace', 'aeroblast', 
//     'after-you', 'agility', 'air-cutter', 'air-slash', 'ally-switch', 'amnesia', 'anchor-shot', 'ancient-power', 'aqua-jet', 'aqua-ring', 'aqua-tail', 
//     'arm-thrust', 'aromatherapy', 'aromatic-mist', 'assist', 'assurance', 'astonish', 'attack-order', 'attract', 'aura-sphere', 
//     'aurora-beam', 'aurora-veil', 'autotomize', 'avalanche', 'baby-doll-eyes', 'barrage', 'baneful-bunker', 'barrier', 'baton-pass', 'beak-blast', 'beat-up', 'belch', 'belly-drum', 
//     'bestow', 'bide', 'bind', 'bite', 'blast-burn', 'blaze-kick', 'blizzard', 'block', 'blue-flare', 'body-slam', 'bolt-strike', 'bone-club', 
//     'bonemerang', 'bone-rush', 'boomburst', 'bounce', 'bouncy-bubble', 'brave-bird', 'brick-break', 'brine', 'bubble', 'bubble-beam', 'bug-bite', 'bug-buzz', 
//     'bulk-up', 'bulldoze','bullet-punch', 'bullet-seed', 'burn-up', 'calm-mind', 'camoflague', 'captivate', 'celebrate', 'charge', 'charge-beam', 
//     'charm', 'chatter', 'chip-away', 'circle-throw', 'clamp', 'clear-smog', 'close-combat', 'clanging-scales', 'coil', 'comet-punch', 'confide', 'confuse-ray', 
//     'confusion', 'constrict', 'conversion', 'conversion-2', 'copycat', 'core-enforcer', 'cosmic-power', 'cotton-guard', 'cotton-spore', 'counter', 'covet', 
//     'crabhammer', 'crafty-shield', 'cross-chop', 'cross-poison', 'crunch', 'crush-claw', 'crush-grip', 'curse', 'cut', 'dark-pulse', 
//     'dark-void', 'darkest-lariat', 'dazzling-gleam', 'defense-curl', 'defend-order', 'defog', 'destiny-bond', 'detect', 'diamond-storm', 'dig', 'disable', 
//     'disarming-voice', 'discharge', 'dive', 'dizzy-punch', 'doom-desire', 'double-iron-bash', 'double-hit', 'double-edge', 'double-kick', 'double-slap', 
//     'double-team', 'draco-meteor', 'dragon-ascent', 'dragon-breath', 'dragon-claw', 'dragon-dance', 'dragon-hammer', 'dragon-rage', 'dragon-rush', 
//     'dragon-pulse', 'dragon-tail', 'drain-punch', 'draining-kiss', 'dream-eater', 'drill-peck', 'drill-run', 'dual-chop', 'dynamic-punch', 
//     'earth-power', 'earthquake', 'echoed-voice', 'eerie-impulse', 'egg-bomb', 'electric-terrain', 'electrify', 'electro-ball', 
//     'electroweb', 'embargo', 'ember', 'encore', 'endeavor', 'endure', 'energy-ball', 'entrainment', 'eruption', 'explosion', 'extrasensory', 
//     'extreme-speed', 'facade', 'fairy-lock', 'fairy-wind', 'feint-attack', 'fake-out', 'fake-tears', 'false-swipe', 'feather-dance', 
//     'feint', 'fell-stinger', 'fiery-dance', 'final-gambit', 'fire-lash', 'fire-fang', 'fire-blast', 'fire-pledge', 'fire-punch', 'fire-spin', 'first-impression', 'fissure', 
//     'flail', 'flame-burst', 'flame-charge', 'flamethrower', 'flame-wheel', 'flare-blitz', 'flash', 'flash-cannon', 'flatter', 'fling', 'fleur-cannon', 'floral-healing',
//     'flower-shield', 'fly', 'flying-press', 'focus-blast', 'focus-energy', 'focus-punch', 'follow-me', 'force-palm', 'forests-curse', 
//     'foresight', 'foul-play', 'freeze-shock', 'freeze-dry', 'frenzy-plant', 'frost-breath', 'frustration', 'fury-attack', 'fury-cutter', 
//     'fury-swipes', 'fusion-bolt', 'fusion-flare', 'future-sight', 'gastro-acid', 'gear-grind', 'geomancy', 'giga-drain', 'giga-impact', 
//     'glaciate', 'glare', 'grass-knot', 'grass-pledge', 'grass-whistle', 'grassy-terrain','gravity', 'growl', 'growth', 'grudge', 
//     'guard-split', 'guard-swap', 'guillotine', 'gunk-shot', 'gust', 'gyro-ball', 'hail', 'hammer-arm', 'happy-hour', 'harden', 'haze', 
//     'headbutt', 'head-charge', 'head-smash', 'heal-bell', 'heal-block', 'heal-order', 'heal-pulse', 'healing-wish', 'heart-swap', 
//     'heart-stamp', 'heat-crash', 'heat-wave', 'heavy-slam', 'helping-hand', 'hex', 'hidden-power', 'high-horsepower', 'high-jump-kick', 'hold-back', 
//     'hold-hands', 'hone-claws', 'horn-attack', 'horn-drill', 'horn-leech', 'howl', 'hurricane', 'hydro-cannon', 'hydro-pump', 'hyper-beam', 
//     'hyper-fang', 'hyper-voice', 'hyperspace-fury', 'hyperspace-hole', 'hypnosis', 'ice-ball', 'ice-beam', 'ice-punch', 'ice-hammer', 'ice-shard', 
//     'ice-burn', 'ice-fang', 'icicle-crash', 'icicle-spear', 'icy-wind', 'imprison', 'incinerate', 'inferno', 'ingrain', 'instruct', 'ion-deluge', 
//     'iron-defense', 'iron-head', 'iron-tail', 'judgement', 'jump-kick', 'karate-chop', 'kinesis', 'kings-shield', 'knock-off', 
//     'lands-wrath', 'laser-focus', 'last-resort', 'lava-plume', 'leafage', 'leaf-blade', 'leaf-storm', 'leaf-tornado', 'leech-life', 'leech-seed', 'leer', 'lick', 
//     'light-of-ruin', 'light-screen', 'liquidation', 'lock-on', 'lovely-kiss', 'low-kick', 'low-sweep', 'lucky-chant', 'lunar-dance', 'luster-purge', 
//     'mach-punch', 'magic-coat', 'magic-room', 'magical-leaf', 'magnitude', 'magma-storm', 'magnet-bomb', 'magnet-rise', 'magnetic-flux', 
//     'mean-look', 'mat-block', 'meditate', 'me-first', 'mega-drain', 'mega-kick', 'mega-punch','megahorn', 'memento', 'metal-burst', 
//     'metal-claw', 'metal-sound', 'meteor-mash', 'metronome', 'milk-drink', 'mimic', 'mind-blown', 'mind-reader', 'minimize', 'miracle-eye', 
//     'mirror-coat', 'mirror-move', 'mirror-shot', 'mist', 'mist-ball', 'misty-terrain', 'moonblast', 'moongeist-beam', 'moonlight', 'morning-sun', 'mud-bomb', 
//     'mud-sport', 'mud-slap', 'muddy-water', 'mud-shot', 'multi-attack', 'mystical-fire', 'nasty-plot', 'natural-gift', 'nature-power', 'natures-madness', 'needle-arm', 
//     'night-daze', 'night-slash', 'nightmare', 'night-shade', 'noble-roar', 'nuzzle', 'oblivion-wing','octazooka', 'odor-sleuth', 'outrage', 
//     'ominous-wind', 'origin-pulse', 'overheat', 'pain-split', 'parabolic-charge', 'parting-shot', 'pay-day', 'payback', 'peck', 
//     'perish-song', 'petal-blizzard', 'petal-dance', 'phantom-force', 'pin-missile', 'play-nice', 'play-rough', 'pluck', 'poison-fang', 
//     'poison-jab', 'poison-gas', 'poison-tail', 'poison-powder', 'poison-sting', 'pound', 'powder', 'powder-snow', 'power-gem', 
//     'power-swap', 'power-trick', 'power-whip', 'power-split', 'power-up-punch', 'precipice-blades', 'present', 'protect', 'psybeam', 
//     'psychic', 'psych-up', 'psycho-boost', 'psycho-cut', 'psycho-shift', 'psyshock', 'psystrike', 'psywave', 'punishment', 'pursuit', 
//     'quash', 'quick-attack', 'quick-guard', 'quiver-dance', 'rage', 'rage-powder', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-shell', 
//     'razor-wind', 'recover', 'recycle', 'reflect', 'reflect-type', 'refresh', 'relic-song', 'rest', 'return', 'revenge', 'retaliate', 
//     'reversal', 'roar', 'roar-of-time', 'rock-blast', 'rock-tomb', 'rock-climb', 'rock-polish', 'rock-wrecker', 'rock-slide', 'rock-smash', 
//     'rock-throw', 'rolling-kick', 'roleplay', 'rollout', 'roost', 'rototiller', 'round', 'sacred-fire', 'sacred-sword', 'safeguard', 
//     'sand-tomb', 'sand-attack', 'sandstorm', 'scald', 'scary-face', 'scratch', 'screech', 'searing-shot', 'secret-power', 'secret-sword', 
//     'seed-bomb', 'seed-flare', 'seismic-toss', 'self-destruct', 'shadow-ball', 'shadow-claw', 'shadow-force', 'shadow-sneak', 'shadow-punch', 
//     'sharpen', 'sheer-cold', 'shell-smash', 'shift-gear', 'shock-wave', 'signal-beam', 'simple-beam', 'silver-wind', 'sing', 'sketch', 
//     'skill-swap', 'skull-bash', 'sky-attack', 'sky-drop', 'sky-uppercut', 'slack-off', 'slam', 'slash', 'sleep-powder', 'sleep-talk', 
//     'sludge', 'sludge-bomb', 'sludge-wave', 'smack-down', 'smog', 'smelling-salts', 'snarl', 'snatch', 'snore', 'smokescreen', 'soak', 
//     'soft-boiled', 'spacial-rend', 'solar-beam', 'sonic-boom', 'spark', 'spider-web', 'spike-cannon', 'spikes', 'spiky-shield', 'spit-up', 
//     'spite', 'splash', 'spore', 'stealth-rock', 'steam-eruption', 'steamroller', 'steel-wing', 'sticky-web', 'stockpile', 'stomp', 
//     'stone-edge', 'stored-power', 'storm-throw', 'strength', 'string-shot', 'struggle', 'struggle-bug', 'stun-spore', 'submission', 
//     'substitute', 'sucker-punch', 'sunny-day', 'super-fang', 'supersonic', 'superpower', 'surf', 'swagger', 'swallow', 'sweet-kiss', 
//     'sweeet-scent', 'swift', 'switcheroo', 'swords-dance', 'synchronoise', 'synthesis', 'tackle', 'tail-glow', 'tail-slap', 'tail-whip', 
//     'tailwind', 'take-down', 'taunt', 'techno-blast', 'telekinesis', 'teleport', 'teeter-dance', 'theif', 'thousand-arrows', 
//     'thousand-waves', 'thrash', 'thunder','thunderbolt', 'thunder-punch', 'thunder-fang','thunder-shock', 'thunder-wave', 'tickle', 
//     'topsy-turvy', 'torment', 'toxic', 'toxic-spikes', 'transform', 'tri-attack', 'trick', 'trick-room', 'trick-or-treat', 'triple-kick', 
//     'trump-card', 'twister', 'twineedle', 'u-turn', 'uproar', 'v-create','vacuum-wave', 'venom-drench', 'venoshock', 'vice-grip', 
//     'vine-whip', 'vital-throw', 'volt-switch', 'volt-tackle', 'wake-up-slap', 'waterfall', 'water-gun', 'water-pulse', 'water-pledge', 
//     'water-sport', 'water-shuriken', 'water-spout', 'whirlwind', 'whirlpool', 'weather-ball', 'wide-guard', 'wild-charge', 'wing-attack', 
//     'withdraw', 'wood-hammer', 'wonder-room', 'work-up', 'worry-seed', 'wrap', 'wring-out', 'will-o-wisp', 'wish', 'x-scissor', 'yawn', 
//     'zap-cannon', 'zen-headbutt'];

// export const generation8Moves = [];
export const generation9Moves = ['absorb', 'accelerock', 'acid', 'acid-armor', 'acid-spray', 'acrobatics', 'acupressure', 'aerial-ace', 
    'aeroblast', 'after-you', 'agility', 'air-cutter', 'air-slash', 'alluring-voice', 'ally-switch', 'amnesia', 'anchor-shot', 
    'ancient-power', 'apple-acid', 'aqua-cutter', 'aqua-jet', 'aqua-ring', 'aqua-step', 'aqua-tail', 'arm-thrust', 'armor-cannon', 
    'aromatic-mist', 'assurance', 'astonish', 'astral-barrage', 'attack-order', 'attract', 'aura-sphere', 'aura-wheel', 'aurora-beam', 
    'aurora-veil', 'avalanche', 'axe-kick', 'baby-doll-eyes', 'baneful-bunker', 'barb-barrage', 'baton-pass', 'beak-blast', 'beat-up', 
    'behemoth-bash', 'behemoth-blade', 'belch', 'belly-drum', 'bestow', 'bind', 'bite', 'bitter-blade', 'bitter-malice', 'blast-burn', 
    'blaze-kick', 'bleakwind-storm', 'blizzard', 'block', 'blood-moon', 'blue-flare', 'body-press', 'body-slam', 'bolt-beak', 'bolt-strike', 
    'bone-club', 'bone-rush', 'bonemerang', 'boomburst', 'bounce', 'branch-poke', 'brave-bird', 'breaking-swipe', 'brick-break', 'brine', 
    'brutal-swing', 'bubble-beam', 'bug-bite', 'bug-buzz', 'bulk-up', 'bulldoze', 'bullet-punch', 'bullet-seed', 'burn-up', 'burning-bulwark', 
    'burning-jealousy', 'ceaseless-edge', 'celebrate', 'charge', 'charge-beam', 'charm', 'chatter', 'chilling-water', 'chilly-reception', 
    'chloroblast', 'circle-throw', 'clanging-scales', 'clangourous-soul', 'clear-smog', 'close-combat', 'coaching', 'coil', 'collision-course', 
    'comeuppance', 'confide', 'confuse-ray', 'confusion', 'conversion', 'conversion-2', 'copycat', 'core-enforcer', 'corrosive-gas', 
    'cosmic-power', 'cotton-guard', 'cotton-spore', 'counter', 'court-change', 'covet', 'crabhammer', 'cross-chop', 'cross-poison', 'crunch', 
    'crush-claw', 'crush-grip', 'curse', 'cut', 'dark-pulse', 'dark-void', 'darkest-lariat', 'dazzling-gleam', 'decorate', 'defend-order', 
    'defense-curl', 'defog', 'destiny-bond', 'detect', 'diamond-storm', 'dig', 'dire-claw', 'disable', 'disarming-voice', 'discharge', 'dive', 
    'doodle', 'doom-desire', 'double-hit', 'double-iron-bash', 'double-kick', 'double-shock', 'double-team', 'double-edge', 'draco-meteor', 
    'dragon-ascent', 'dragon-breath', 'dragon-cheer', 'dragon-claw', 'dragon-darts', 'dragon-energy', 'dragon-hammer', 'dragon-pulse', 
    'dragon-rush', 'dragon-tail', 'drain-punch', 'draining-kiss', 'dream-eater', 'drill-peck', 'drill-rush', 'drum-beating', 'dual-wingbeat', 
    'dynamax-cannon', 'dynamic-punch', 'earth-power', 'earthquake', 'echoed-voice', 'eerie-impulse', 'eerie-spell', 'electric-terrain', 
    'electrify', 'electro-ball', 'electro-drift', 'electro-shot', 'electroweb', 'ember', 'encore', 'endeavor', 'endure', 'energy-ball', 
    'entrainment', 'eruption', 'esper-wing', 'expanding-force', 'explosion', 'extrasensory', 'extreme-speed', 'facade', 'fairy-lock', 
    'fairy-wind', 'fake-out', 'fake-tears', 'false-surrender', 'false-swipe', 'feather-dance', 'feint', 'fell-stinger', 'fickle-beam', 
    'fiery-dance', 'fiery-wrath', 'fillet-away', 'final-gambit', 'fire-blast', 'fire-fang', 'fire-lash', 'fire-pledge', 'fire-punch', 
    'fire-spin', 'first-impression', 'fishious-rend', 'fissure', 'flail', 'flame-charge', 'flame-wheel', 'flamethrower', 'flare-blitz', 
    'flash-cannon', 'flatter', 'fleur-cannon', 'fling', 'flip-turn', 'floral-healing', 'flower-trick', 'fly', 'flying-press', 'focus-blast', 
    'focus-energy', 'focus-punch', 'follow-me', 'force-palm', 'forests-curse', 'foul-play', 'freeze-shock', 'freeze-dry', 'freezing-glare', 
    'frenzy-plant', 'frost-breath', 'fury-attack', 'fury-cutter', 'fury-swipes', 'fusion-bolt', 'fusion-flare', 'future-sight', 'gastro-acid', 
    'gear-grind', 'gear-up', 'geomancy', 'giga-drain', 'giga-impact', 'gigaton-hammer', 'glacial-lance', 'glaciate', 'glaive-rush', 'glare', 
    'grass-knot', 'grass-pledge', 'grass-whistle', 'grassy-glide', 'grassy-terrain', 'grav-apple', 'gravity', 'growl', 'growth', 'guard-split', 
    'guard-swap', 'guillotine', 'gunk-shot', 'gust', 'gyro-ball', 'hammer-arm', 'happy-hour', 'hard-press', 'harden', 'haze', 'head-charge', 
    'head-smash', 'headbutt', 'headlong-rush', 'heal-bell', 'heal-block', 'heal-order', 'heal-pulse', 'healing-wish', 'heart-swap', 'heat-crash', 
    'heat-wave', 'heavy-slam', 'helping-hand', 'hex', 'high-horsepower', 'high-jump-kick', 'hold-back', 'hold-hands', 'hone-claws', 'horn-attack', 
    'horn-drill', 'horn-leech', 'howl', 'hurricane', 'hydro-cannon', 'hydro-pump', 'hydro-steam', 'hyper-beam', 'hyper-drill', 'hyper-voice', 
    'hyperspace-fury', 'hyperspace-hole', 'hypnosis', 'ice-beam', 'ice-burn', 'ice-fang', 'ice-hammer', 'ice-punch', 'ice-shard', 'ice-spinner', 
    'icicle-crash', 'icicle-spear', 'icy-wind', 'imprison', 'incinerate', 'infernal-parade', 'inferno', 'infestation', 'ingrain', 'instruct', 
    'iron-defense', 'iron-head', 'iron-tail', 'ivy-cudgel', 'jaw-lock', 'jet-punch', 'judgement', 'jungle-healing', 'kinesis', 'kings-shield', 
    'knock-off', 'kowtow-cleave', 'lands-wrath', 'laser-focus', 'lash-out', 'last-resort', 'last-respects', 'lava-plume', 'leaf-blade', 'leaf-storm', 
    'leafage', 'leech-life', 'leech-seed', 'leer', 'lick', 'life-dew', 'light-screen', 'light-of-ruin', 'liquidation', 'lock-on', 'lovely-kiss', 
    'low-kick', 'low-sweep', 'lumina-crash', 'lunar-blessing', 'lunar-dance', 'lunge', 'luster-purge', 'mach-punch', 'magic-powder', 'magic-room', 
    'magical-leaf', 'magma-storm', 'magnet-rise', 'magnetic-flux', 'make-it-rain', 'malignant-chain', 'mat-block', 'matcha-gotcha', 'me-first', 
    'mean-look', 'mega-drain', 'mega-kick', 'mega-punch', 'megahorn', 'memento', 'metal-burst', 'metal-claw', 'metal-sound', 'meteor-assualt', 
    'meteor-beam', 'metronome', 'mighty-cleave', 'milk-drink', 'mimic', 'mind-blown', 'minimize', 'mirror-coat', 'mist', 'mist-ball', 
    'misty-explosion', 'misty-terrain', 'moonblast', 'moongeist-beam', 'moonlight', 'morning-sun', 'mortal-spin', 'mountain-gale', 'mud-shot', 
    'mud-slap', 'muddy-water', 'multi-attack', 'mystical-fire', 'mystical-power', 'nasty-plot', 'natures-madness', 'night-daze', 'night-shade', 
    'night-slash', 'no-retreat', 'noble-roar', 'nuzzle', 'oblivion-wing', 'obstruct', 'octazooka', 'octolock', 'order-up', 'origin-pulse', 'outrage', 
    'overdrive', 'overheat', 'pain-split', 'parabolic-charge', 'parting-shot', 'pay-day', 'payback', 'peck', 'perish-song', 'petal-blizzard', 
    'petal-dance', 'phantom-force', 'photon-geyser', 'pin-missile', 'plasma-fists', 'play-nice', 'play-rough' , 'pluck', 'poison-fang', 'poison-gas', 
    'poison-jab', 'poison-powder', 'poison-sting', 'poison-tail', 'pollen-puff', 'poltergeist', 'population-bomb', 'pounce', 'pound', 'powder-snow', 
    'power-gem', 'power-shift', 'power-split', 'power-swap', 'power-trick', 'power-trip', 'power-whip', 'power-up-punch', 'precipice-blades', 
    'present', 'prismatic-laser', 'protect', 'psybeam', 'psyblade', 'psych-up', 'psychic', 'psychic-fangs', 'psychic-noise', 'psychic-terrain', 
    'psycho-boost', 'psycho-cut', 'psyshield-bash', 'psyshock', 'psystrike', 'purify', 'pyro-ball', 'quash', 'quick-attack', 'quick-guard', 
    'quiver-dance', 'rage-fist', 'rage-powder', 'raging-bull', 'raging-fury', 'rain-dance', 'rapid-spin', 'razor-leaf', 'razor-shell', 'recover', 
    'recycle', 'reflect', 'reflect-type', 'relic-song', 'rest', 'retaliate', 'revelation-dance', 'reversal', 'revival-blessing', 'rising-voltage', 
    'roar', 'roar-of-time', 'rock-blast', 'rock-polish', 'rock-slide', 'rock-smash', 'rock-throw', 'rock-tomb', 'rock-wrecker', 'role-play', 
    'rollout', 'roost', 'round', 'ruination', 'sacred-fire', 'sacred-sword', 'safeguard', 'salt-cure', 'sand-attack', 'sand-tomb', 'sandsear-storm', 
    'sandstorm', 'sappy-seed', 'scald', 'scale-shot', 'scary-face', 'scorching-sands', 'scratch', 'screech', 'searing-shot', 'secret-sword', 
    'seed-bomb', 'seed-flare', 'seismic-toss', 'self-destruct', 'shadow-ball', 'shadow-bone', 'shadow-claw', 'shadow-force', 'shadow-punch', 
    'shadow-sneak', 'shed-tail', 'sheer-cold', 'shell-side-arm', 'shell-smash', 'shell-trap', 'shelter', 'shift-gear', 'shock-wave', 'shore-up', 
    'silk-trap', 'simple-beam', 'sing', 'sketch', 'skill-swap', 'skitter-smack', 'sky-attack', 'sky-drop', 'sky-uppercut', 'slack-off', 'slam', 
    'slash', 'sleep-powder', 'sleep-talk', 'sludge', 'sludge-bomb', 'sludge-wave', 'smack-down', 'smart-strike', 'smog', 'smokescreen', 'snap-trap', 
    'snarl', 'snipe-shot', 'snore', 'snowscape', 'soak', 'soft-boiled', 'solar-beam', 'solar-blade', 'spacial-rend', 'spark', 'sparkling-aria', 
    'spectral-theif', 'speed-swap', 'spicy-extract', 'spikes', 'spiky-shield', 'spin-out', 'spirit-break', 'spirit-shackle', 'spit-up', 'spite', 
    'splash', 'spore', 'springtide-storm', 'stealth-rock', 'steam-eruption', 'steel-beam', 'steel-roller', 'steel-wing', 'sticky-web', 'stockpile', 
    'stomp', 'stomping-tantrum', 'stone-axe', 'stone-edge', 'stored-power', 'strange-steam', 'storm-throw', 'strength', 'strength-sap', 
    'string-shot', 'struggle', 'struggle-bug', 'stuff-cheeks', 'stun-spore', 'substitute', 'sucker-punch', 'sunny-day', 'sunsteel-strike', 
    'super-fang', 'supercell-slam', 'superpower', 'supersonic', 'surf', 'surging-strikes', 'swagger', 'swallow', 'sweet-kiss', 'sweet-scent', 
    'swift', 'switcheroo', 'swords-dance', 'synthesis', 'syrup-bomb', 'tachyon-cutter', 'tackle', 'tail-glow', 'tail-slap', 'tail-whip', 'tailwind', 
    'take-down', 'take-heart', 'tar-shot', 'taunt', 'tearful-look', 'teatime', 'techno-blast', 'teeter-dance', 'teleport', 'temper-flare', 
    'tera-blast', 'tera-starstorm', 'terrain-pulse', 'thief', 'thousand-arrows', 'thousand-waves', 'thrash', 'throat-chop', 'thunder', 'thunderbolt', 
    'thunderclap', 'thunder-cage', 'thunder-fang', 'thunder-punch', 'thunder-shock', 'thunder-wave', 'thunderous-kick', 'tickle', 'tidy-up', 
    'topsy-turvy', 'torch-song', 'torment', 'toxic', 'toxic-spikes', 'toxic-thread', 'trailblaze', 'transform', 'tri-attack', 'trick', 'trick-room', 
    'trick-or-treat', 'triple-arrows', 'triple-axel', 'triple-dive', 'triple-kick', 'trop-kick', 'twin-beam', 'twister', 'u-turn', 'upper-hand', 
    'uproar', 'v-create', 'vacuum-wave', 'venoshock', 'victory-dance', 'vine-whip', 'vise-grip', 'volt-switch', 'volt-tackle', 'water-gun', 
    'water-pledge', 'water-pulse', 'water-shuriken', 'water-spout', 'waterfall', 'wave-crash', 'weather-ball', 'whirlpool', 'whirlwind', 
    'wicked-blow', 'wide-guard', 'wild-charge', 'wildbolt-storm', 'will-o-wisp', 'wing-attack', 'wish', 'withdraw', 'wonder-room', 'wood-hammer', 
    'work-up', 'worry-seed', 'wrap', 'x-scissor', 'yawn', 'zap-cannon', 'zen-headbutt', 'zing-zap'];